# Generated by Django 4.2.1 on 2023-07-26 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 23, 11, 22, 230009), editable=False, verbose_name='Regdate'),
        ),
    ]
