# Generated by Django 4.2.1 on 2023-06-10 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentistDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=200, verbose_name='Details')),
                ('medicine_name', models.CharField(max_length=300, verbose_name='Medicine Name')),
                ('medicine_time', models.CharField(max_length=50, verbose_name='Medicine Time')),
                ('medicine_period', models.CharField(max_length=50, verbose_name='Medicine Period')),
                ('medicine_tfood', models.CharField(max_length=50, verbose_name='Medicine T-Food')),
                ('medicine_no', models.CharField(max_length=20, verbose_name='Medicine No')),
                ('idappointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.appointment')),
            ],
        ),
    ]
