# Generated by Django 4.2.1 on 2023-07-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orthodontics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('yes_no_field', models.CharField(max_length=100)),
                ('material_field', models.CharField(max_length=100)),
                ('width_field', models.CharField(max_length=100)),
            ],
        ),
    ]
