# Generated by Django 4.2.1 on 2023-08-13 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='app_data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reception',
            name='days',
            field=models.CharField(max_length=20, null=True, verbose_name='Days'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='doctor_name',
            field=models.CharField(max_length=120, verbose_name='doctor_name'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 15, 46, 3, 206929), editable=False, verbose_name='Regdate'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
