# Generated by Django 4.2.1 on 2023-08-14 23:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oralsurgery',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='exo_images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='phone',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='photo',
            name='oral_surgery_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.oralsurgery'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 23, 13, 14, 640470), editable=False, verbose_name='Regdate'),
        ),
    ]
