# Generated by Django 4.2.1 on 2023-07-16 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exo',
            name='exo_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='exo',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 2, 1, 27, 554495), editable=False, verbose_name='Regdate'),
        ),
        migrations.AlterField(
            model_name='medicin',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 2, 1, 27, 555491), editable=False, verbose_name='Regdate'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 2, 1, 27, 555491), editable=False, verbose_name='Regdate'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 2, 1, 27, 553498), editable=False, verbose_name='Regdate'),
        ),
    ]
