# Generated by Django 4.2.1 on 2023-08-13 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_reception_app_data_reception_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 16, 4, 41, 456219), editable=False, verbose_name='Regdate'),
        ),
    ]
