# Generated by Django 4.2.1 on 2023-07-17 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_exo_exo_image_alter_exo_regdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exo',
            old_name='exo_image',
            new_name='exo_images',
        ),
        migrations.AlterField(
            model_name='exo',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 21, 52, 41, 889871), editable=False, verbose_name='Regdate'),
        ),
        migrations.AlterField(
            model_name='medicin',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 21, 52, 41, 890868), editable=False, verbose_name='Regdate'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 21, 52, 41, 890868), editable=False, verbose_name='Regdate'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 17, 21, 52, 41, 887880), editable=False, verbose_name='Regdate'),
        ),
    ]
