# Generated by Django 4.2.1 on 2023-08-17 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_oralsurgery_date_of_birth_oralsurgery_exo_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oralsurgery',
            name='no_unite',
            field=models.IntegerField(blank=True, null=True, verbose_name='no_unite'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 23, 39, 36, 473843), editable=False, verbose_name='Regdate'),
        ),
    ]
