# Generated by Django 4.2.1 on 2023-07-27 00:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_exo_price_alter_oralsurgery_regdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 0, 59, 19, 948273), editable=False, verbose_name='Regdate'),
        ),
        migrations.CreateModel(
            name='Crown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('phone', models.CharField(max_length=120, verbose_name='Phone')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('date_of_birth', models.CharField(max_length=20, verbose_name='Gender')),
                ('shade', models.CharField(blank=True, max_length=120, verbose_name='shade')),
                ('no_unite', models.CharField(blank=True, max_length=120, verbose_name='no_unite')),
                ('color', models.CharField(blank=True, max_length=120, verbose_name='color')),
                ('no_prepare', models.CharField(blank=True, max_length=120, verbose_name='no_prepare')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='price')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='note')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Regdate')),
                ('exo_images', models.ImageField(blank=True, null=True, upload_to='')),
                ('idReception', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception')),
            ],
        ),
    ]
