# Generated by Django 4.2.1 on 2023-08-19 23:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_oralsurgery_no_unite_alter_oralsurgery_regdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 19, 23, 43, 56, 591799), editable=False, verbose_name='Regdate'),
        ),
        migrations.CreateModel(
            name='GaveAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=20, null=True, verbose_name='Days')),
                ('time', models.CharField(max_length=200, null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Regdate')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.doctors')),
            ],
        ),
    ]
