# Generated by Django 4.2.1 on 2023-07-27 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_oralsurgery_regdate_crown'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='crown_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.crown'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 27, 10, 34, 45, 450508), editable=False, verbose_name='Regdate'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='exo_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.exo'),
        ),
    ]
