# Generated by Django 4.2.1 on 2023-08-20 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_oralsurgery_regdate_gaveappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaveappointment',
            name='app_data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 0, 42, 41, 522629), editable=False, verbose_name='Regdate'),
        ),
    ]
