# Generated by Django 4.2.1 on 2023-07-19 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_exo_exo_images_alter_exo_regdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exo',
            name='exo_images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='medicin',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Regdate'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 16, 6, 49, 125610), editable=False, verbose_name='Regdate'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Regdate'),
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('doze', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('times', models.CharField(max_length=200)),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Regdate')),
                ('idReception', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception')),
            ],
        ),
    ]
