# Generated by Django 4.2.1 on 2023-08-20 01:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_gaveappointment_app_data_alter_oralsurgery_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaveappointment',
            name='date_of_birth',
            field=models.CharField(max_length=20, null=True, verbose_name='date_of_birth'),
        ),
        migrations.AddField(
            model_name='gaveappointment',
            name='gender',
            field=models.CharField(max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='gaveappointment',
            name='idReception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception'),
        ),
        migrations.AddField(
            model_name='gaveappointment',
            name='name',
            field=models.CharField(max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='gaveappointment',
            name='phone',
            field=models.CharField(max_length=120, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 20, 1, 6, 47, 13340), editable=False, verbose_name='Regdate'),
        ),
    ]
