# Generated by Django 4.2.1 on 2023-07-19 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_exo_exo_images_alter_medicin_regdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_medicine', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 19, 10, 41, 980833), editable=False, verbose_name='Regdate'),
        ),
    ]
