# Generated by Django 4.2.1 on 2023-07-19 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_medicine1_alter_oralsurgery_regdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine1',
            name='name_medicine',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 19, 19, 15, 21, 637234), editable=False, verbose_name='Regdate'),
        ),
    ]
