# Generated by Django 4.2.1 on 2023-08-25 20:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_gaveappointment_date_of_birth_gaveappointment_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 20, 35, 37, 845463), editable=False, verbose_name='Regdate'),
        ),
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='totalPrice')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='paid')),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='remaining')),
                ('regDate', models.DateTimeField(auto_now_add=True, verbose_name='RegDate')),
                ('idCrown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.crown')),
                ('idExo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.exo')),
                ('idFilling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.filling')),
                ('idOralSurgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.oralsurgery')),
                ('idReception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reception')),
                ('idVeneer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.veneer')),
            ],
        ),
    ]
