# Generated by Django 4.2.1 on 2023-07-24 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_medicine1_name_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='doctor_name',
            field=models.CharField(max_length=200, null=True, verbose_name='doctor_name'),
        ),
        migrations.AddField(
            model_name='reception',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 24, 23, 37, 59, 625314), editable=False, verbose_name='Regdate'),
        ),
    ]
