# Generated by Django 4.2.1 on 2023-08-25 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_oralsurgery_regdate_debts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 20, 35, 51, 508851), editable=False, verbose_name='Regdate'),
        ),
    ]
