# Generated by Django 4.2.1 on 2023-08-31 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_oralsurgery_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exo',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='paid'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 20, 39, 12, 808833), editable=False, verbose_name='Regdate'),
        ),
    ]
