# Generated by Django 4.2.1 on 2023-09-01 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_exo_paid_alter_oralsurgery_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='crown',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='paid'),
        ),
        migrations.AddField(
            model_name='filling',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='paid'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='paid'),
        ),
        migrations.AddField(
            model_name='veneer',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='paid'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 1, 21, 37, 55, 848923), editable=False, verbose_name='Regdate'),
        ),
    ]
