# Generated by Django 4.2.1 on 2023-09-08 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_basicinfo_alter_oralsurgery_regdate_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='month',
            field=models.PositiveIntegerField(null=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 23, 2, 16, 639525), editable=False, verbose_name='Regdate'),
        ),
    ]
