# Generated by Django 4.2.1 on 2023-09-08 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_salary_month_alter_oralsurgery_regdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 23, 18, 12, 644953), editable=False, verbose_name='Regdate'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.CharField(max_length=120, null=True, verbose_name='Month'),
        ),
    ]
