# Generated by Django 4.2.1 on 2023-09-11 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_oralsurgery_regdate_alter_salary_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.CharField(max_length=120, verbose_name='fullname')),
                ('invoice_date', models.DateField(null=True)),
                ('type', models.CharField(max_length=120, verbose_name='fullname')),
                ('description', models.CharField(max_length=120, verbose_name='fullname')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='finalSalary')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Regdate')),
            ],
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 11, 10, 12, 43, 877226), editable=False, verbose_name='Regdate'),
        ),
    ]
