# Generated by Django 4.2.1 on 2023-09-12 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_outcome_alter_oralsurgery_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='salaryPaid',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='salaryPaid'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 12, 12, 53, 7, 722541), editable=False, verbose_name='Regdate'),
        ),
    ]
