# Generated by Django 4.2.1 on 2023-10-26 23:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_basicinfo_salarypaid_alter_oralsurgery_regdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 26, 23, 56, 24, 577266), editable=False, verbose_name='Regdate'),
        ),
        migrations.CreateModel(
            name='Endo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('phone', models.CharField(max_length=120, verbose_name='Phone')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('date_of_birth', models.CharField(max_length=20, verbose_name='date_of_birth')),
                ('first_visit', models.CharField(max_length=20, verbose_name='date_of_birth')),
                ('components_first', models.CharField(blank=True, max_length=120, null=True, verbose_name='components')),
                ('ur', models.CharField(blank=True, max_length=120, null=True, verbose_name='ur')),
                ('ul', models.CharField(blank=True, max_length=120, null=True, verbose_name='ul')),
                ('lr', models.CharField(blank=True, max_length=120, null=True, verbose_name='lr')),
                ('ll', models.CharField(blank=True, max_length=120, null=True, verbose_name='ll')),
                ('no_prepare', models.IntegerField(verbose_name='no_prepare')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='price')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='paid')),
                ('note', models.CharField(blank=True, max_length=120, null=True, verbose_name='note')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Regdate')),
                ('exo_images', models.ImageField(blank=True, null=True, upload_to='')),
                ('second_visit', models.CharField(max_length=20, verbose_name='date_of_birth')),
                ('components_second', models.CharField(blank=True, max_length=120, null=True, verbose_name='components_second')),
                ('third_visit', models.CharField(max_length=20, verbose_name='date_of_birth')),
                ('components_third', models.CharField(blank=True, max_length=120, null=True, verbose_name='components_third')),
                ('fourth_visit', models.CharField(max_length=20, verbose_name='date_of_birth')),
                ('components_fourth', models.CharField(blank=True, max_length=120, null=True, verbose_name='components_fourth')),
                ('idReception', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='endo_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.endo'),
        ),
    ]
