# Generated by Django 4.2.1 on 2023-10-27 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_oralsurgery_regdate_endo_photo_endo_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='endo',
            name='canal',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='endo',
            name='work_length',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='work_length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 0, 14, 43, 353497), editable=False, verbose_name='Regdate'),
        ),
    ]
