# Generated by Django 4.2.1 on 2023-10-30 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_remove_exo_no_prepare_remove_exo_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ortho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=120, null=True, verbose_name='Phone')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gender')),
                ('date_of_birth', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gender')),
                ('ur', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ul', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lr', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ll', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('urn', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('uln', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lrn', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lln', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('teeth_type', models.CharField(blank=True, max_length=120, null=True, verbose_name='teeth_type')),
                ('angle_class', models.CharField(blank=True, max_length=120, null=True, verbose_name='angle_class')),
                ('over_jet', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('over_bt', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('jow_shift', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('midlin_shift', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('urs', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('uls', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lrs', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lls', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('teeth_size', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('before', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('after', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('treatment_plan', models.TextField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('visit_type', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('wive_size', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('cross_sectional', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('material', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('notes', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('exo_images', models.ImageField(blank=True, null=True, upload_to='')),
                ('regdate', models.DateTimeField(default=datetime.datetime(2023, 10, 30, 13, 40, 2, 553286), editable=False, verbose_name='Regdate')),
                ('idReception', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception')),
            ],
        ),
        migrations.DeleteModel(
            name='Orthodontics',
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 13, 40, 2, 552323), editable=False, verbose_name='Regdate'),
        ),
        migrations.AddField(
            model_name='photo',
            name='ortho_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.ortho'),
        ),
    ]
