# Generated by Django 4.2.1 on 2023-10-30 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_ortho_delete_orthodontics_alter_oralsurgery_regdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ortho',
            name='paid',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='paid'),
        ),
        migrations.AddField(
            model_name='ortho',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 13, 45, 14, 744612), editable=False, verbose_name='Regdate'),
        ),
        migrations.AlterField(
            model_name='ortho',
            name='regdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 13, 45, 14, 745609), editable=False, verbose_name='Regdate'),
        ),
    ]
