# Generated by Django 4.2.1 on 2023-10-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_ortho_paid_ortho_price_alter_oralsurgery_regdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oralsurgery',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Regdate'),
        ),
        migrations.AlterField(
            model_name='ortho',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Regdate'),
        ),
    ]
