# Generated by Django 4.2.1 on 2023-10-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_oralsurgery_regdate_alter_ortho_regdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ortho',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='paid'),
        ),
        migrations.AlterField(
            model_name='ortho',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
    ]
