# Generated by Django 4.2.1 on 2023-10-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_ortho_paid_alter_ortho_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ortho',
            old_name='after',
            new_name='ANB_after',
        ),
        migrations.RenameField(
            model_name='ortho',
            old_name='before',
            new_name='ANB_before',
        ),
        migrations.AddField(
            model_name='ortho',
            name='IMPA_after',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ortho',
            name='IMPA_before',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ortho',
            name='SNA_after',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ortho',
            name='SNA_before',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ortho',
            name='SNB_after',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ortho',
            name='SNB_before',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ortho',
            name='SNGOGN_after',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ortho',
            name='SNGOGN_before',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ortho',
            name='U1_SN_after',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='ortho',
            name='U1_SN_before',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
    ]
