# Generated by Django 4.2.1 on 2023-10-31 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_rename_after_ortho_anb_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_name', models.CharField(max_length=120, verbose_name='visit_name')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Regdate')),
            ],
        ),
        migrations.RemoveField(
            model_name='ortho',
            name='visit_type',
        ),
        migrations.AddField(
            model_name='ortho',
            name='visits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.visits'),
        ),
    ]
