# Generated by Django 4.2.1 on 2023-10-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_visits_remove_ortho_visit_type_ortho_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visits',
            name='visit_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='visit_name'),
        ),
    ]
