# Generated by Django 4.2.1 on 2023-11-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_alter_visits_visit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ortho',
            name='treatment_plan',
            field=models.CharField(blank=True, max_length=245, null=True, verbose_name='Name'),
        ),
    ]
