# Generated by Django 4.2.1 on 2023-11-21 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_ortho_treatment_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_name', models.CharField(max_length=120, verbose_name='educational_name')),
                ('phone', models.CharField(max_length=120, verbose_name='phone')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Regdate')),
            ],
        ),
        migrations.AddField(
            model_name='reception',
            name='educational',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.educational'),
        ),
    ]
