# Generated by Django 4.2.1 on 2023-11-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_exo_total_price_ortho_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='exo',
            name='educational',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.educational'),
        ),
    ]
