# Generated by Django 4.2.1 on 2023-11-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_crown_doctor_crown_educational_endo_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ortho',
            name='brackets',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
    ]
