# Generated by Django 4.2.1 on 2023-11-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_ortho_regdatev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ortho',
            name='regdatev',
        ),
        migrations.AddField(
            model_name='ortho',
            name='visit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visit Date'),
        ),
    ]
