# Generated by Django 4.2.1 on 2023-12-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0047_websitefeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oralsurgery',
            old_name='diameter',
            new_name='diameterll1',
        ),
        migrations.RenameField(
            model_name='oralsurgery',
            old_name='length',
            new_name='lengthll1',
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterll2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterll3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterll4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterlr1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterlr2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterlr3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterlr4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterul1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterul2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterul3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterul4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterur1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterur2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterur3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterur4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthll2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthll3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthll4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthlr1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthlr2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthlr3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthlr4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthul1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthul2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthul3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthul4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthur1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthur2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthur3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthur4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Length'),
        ),
    ]
