# Generated by Django 4.2.1 on 2023-12-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_rename_diameter_oralsurgery_diameterll1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterll5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterll6',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterll7',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterll8',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterlr5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterlr6',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterlr7',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterlr8',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterul5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterul6',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterul7',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterul8',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterur5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterur6',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterur7',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='diameterur8',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthll5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthll6',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthll7',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthll8',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthlr5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthlr6',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthlr7',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthlr8',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthul5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthul6',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthul7',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthul8',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthur5',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthur6',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthur7',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AddField(
            model_name='oralsurgery',
            name='lengthur8',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterll1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterll2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterll3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterll4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterlr1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterlr2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterlr3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterlr4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterul1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterul2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterul3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterul4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterur1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterur2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterur3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='diameterur4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthll1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthll2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthll3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthll4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthlr1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthlr2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthlr3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthlr4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthul1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthul2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthul3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthul4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthur1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthur2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthur3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='oralsurgery',
            name='lengthur4',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Length'),
        ),
    ]
