# Generated by Django 4.2.1 on 2023-12-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_oralsurgery_diameterll5_oralsurgery_diameterll6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ortho',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='ortho',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='price'),
        ),
    ]
