# Generated by Django 4.2.1 on 2023-12-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0053_rename_access_opiningt_endo_components_first_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endo',
            name='first_visit',
            field=models.CharField(max_length=20, null=True, verbose_name='date_of_birth'),
        ),
    ]
