# Generated by Django 4.2.1 on 2023-12-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0054_alter_endo_first_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endo',
            name='first_visit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='date_of_birth'),
        ),
    ]
