# Generated by Django 4.2.1 on 2023-12-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0056_alter_endo_first_visit_alter_filling_no_prepare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filling',
            name='filling_place',
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingll1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingll2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingll3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingll4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingll5',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingll6',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingll7',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingll8',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillinglr1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillinglr2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillinglr3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillinglr4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillinglr5',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillinglr6',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillinglr7',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillinglr8',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingul1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingul2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingul3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingul4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingul5',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingul6',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingul7',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingul8',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingur1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingur2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingur3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingur4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingur5',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingur6',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingur7',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
        migrations.AddField(
            model_name='filling',
            name='fillingur8',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place'),
        ),
    ]
