# Generated by Django 4.2.1 on 2023-12-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0058_exo_remaining_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exo',
            name='remaining_amount',
        ),
        migrations.AddField(
            model_name='exo',
            name='previous_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
