# Generated by Django 4.2.1 on 2023-12-26 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0059_remove_exo_remaining_amount_exo_previous_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exo',
            old_name='previous_date',
            new_name='date',
        ),
    ]
