# Generated by Django 4.2.1 on 2023-12-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0061_crown_date_endo_date_filling_date_oralsurgery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_date', models.DateField(null=True)),
                ('paid_amount', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='paid')),
                ('price', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='paid')),
                ('crown_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.crown')),
                ('idReception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception')),
            ],
        ),
        migrations.CreateModel(
            name='Aveen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crown_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.crown')),
            ],
        ),
    ]
