# Generated by Django 4.2.1 on 2023-12-28 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0062_paymenthistory_aveen'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='endo_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.endo'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='crown_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.crown'),
        ),
    ]
