# Generated by Django 4.2.1 on 2023-12-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0063_paymenthistory_endo_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='filling_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.filling'),
        ),
    ]
