# Generated by Django 4.2.1 on 2023-12-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0064_paymenthistory_filling_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='oral_surgery_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.oralsurgery'),
        ),
    ]
