# Generated by Django 4.2.1 on 2023-12-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0070_paymenthistory_exo_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='phone',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Phone'),
        ),
    ]
