# Generated by Django 4.2.1 on 2024-01-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0073_alter_reception_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ortho',
            name='both_date',
            field=models.DateField(blank=True, null=True, verbose_name='Visit Date'),
        ),
        migrations.AddField(
            model_name='ortho',
            name='lower_date',
            field=models.DateField(blank=True, null=True, verbose_name='Visit Date'),
        ),
        migrations.AddField(
            model_name='ortho',
            name='uper_date',
            field=models.DateField(blank=True, null=True, verbose_name='Visit Date'),
        ),
    ]
