# Generated by Django 4.2.1 on 2024-02-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0074_ortho_both_date_ortho_lower_date_ortho_uper_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ortho',
            name='type_arch',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
    ]
