# Generated by Django 4.2.1 on 2024-02-25 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0075_ortho_type_arch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('phone', models.CharField(max_length=120, verbose_name='phone')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('date_of_birth', models.DateField(null=True)),
                ('app_data', models.DateField(null=True)),
                ('days', models.CharField(max_length=20, null=True, verbose_name='Days')),
                ('time', models.CharField(max_length=200, null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Regdate')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.doctors')),
                ('educational', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.educational')),
                ('idReception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
