# Generated by Django 4.2.1 on 2024-02-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0077_exo_idexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exo',
            old_name='idExo',
            new_name='idReception1',
        ),
    ]
