# Generated by Django 4.2.1 on 2024-06-23 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0088_prosthodontics_idreception1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('phone', models.CharField(max_length=120, verbose_name='Phone')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('date_of_birth', models.CharField(max_length=20, verbose_name='date_of_birth')),
                ('filling_type', models.CharField(blank=True, max_length=120, verbose_name='filling_type')),
                ('fillingurA', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillingurB', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillingurC', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillingurD', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillingurE', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillingulA', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillingulB', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillingulC', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillingulD', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillingulE', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillinglrA', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillinglrB', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillinglrC', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillinglrD', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillinglrE', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillingllA', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillingllB', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillingllC', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillingllD', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('fillingllE', models.CharField(blank=True, max_length=120, null=True, verbose_name='filling_place')),
                ('ur', models.CharField(blank=True, max_length=120, null=True, verbose_name='ur')),
                ('ul', models.CharField(blank=True, max_length=120, null=True, verbose_name='ul')),
                ('lr', models.CharField(blank=True, max_length=120, null=True, verbose_name='lr')),
                ('ll', models.CharField(blank=True, max_length=120, null=True, verbose_name='ll')),
                ('no_prepare', models.IntegerField(blank=True, null=True, verbose_name='no_prepare')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='price')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='price')),
                ('paid', models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='paid')),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Regdate')),
                ('exo_images', models.ImageField(blank=True, null=True, upload_to='')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.doctors')),
                ('educational', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.educational')),
                ('idReception', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception')),
                ('idReception1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception1')),
            ],
        ),
    ]
