# Generated by Django 4.2.1 on 2024-06-23 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0090_photo_pedo_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='pedo_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.pedo'),
        ),
    ]
