# Generated by Django 4.2.1 on 2024-06-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0091_paymenthistory_pedo_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='exo',
            name='center_share',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='exo',
            name='discount_option',
            field=models.CharField(max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='exo',
            name='doctor_share',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='price'),
        ),
    ]
