# Generated by Django 4.2.1 on 2024-06-26 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0092_exo_center_share_exo_discount_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=120, verbose_name='fullname')),
                ('Quantity', models.CharField(max_length=120, verbose_name='fullname')),
                ('shelf_Num', models.CharField(max_length=120, verbose_name='fullname')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8, verbose_name='finalSalary')),
                ('expire_date', models.DateField(verbose_name='Regdate')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Regdate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
