# Generated by Django 4.2.1 on 2024-06-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0093_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='lab',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='lab2',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='proportion_center',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='proportion_doctor',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='price'),
        ),
    ]
