# Generated by Django 4.2.1 on 2024-06-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0094_doctors_lab_doctors_lab2_doctors_proportion_center_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='lab2',
        ),
    ]
