# Generated by Django 4.2.1 on 2024-06-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0095_remove_doctors_lab2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='proportion_center',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='proportion_doctor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
    ]
