# Generated by Django 4.2.1 on 2024-06-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0100_alter_doctors_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=120, verbose_name='material_name')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Regdate')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='material_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
