# Generated by Django 4.2.1 on 2024-07-01 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0101_material_store_material_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='lab',
        ),
    ]
