# Generated by Django 4.2.1 on 2024-07-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0109_alter_store_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialoutput',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.doctors'),
        ),
        migrations.AddField(
            model_name='materialoutput',
            name='material_out',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='materialoutput',
            name='quantity_in',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='fullname'),
        ),
    ]
