# Generated by Django 4.2.1 on 2024-07-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0110_materialoutput_doctor_materialoutput_material_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialoutput',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='materialoutput',
            name='quantity_in',
            field=models.IntegerField(default=0),
        ),
    ]
