# Generated by Django 4.2.1 on 2024-07-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0111_alter_materialoutput_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exo',
            name='name_lab',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='exo',
            name='price_lab',
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True, verbose_name='price'),
        ),
    ]
