# Generated by Django 4.2.1 on 2024-07-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0112_exo_name_lab_exo_price_lab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exo',
            old_name='name_lab',
            new_name='lab_name',
        ),
    ]
