# Generated by Django 4.2.1 on 2024-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0113_rename_name_lab_exo_lab_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exo',
            name='center_share',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='exo',
            name='doctor_share',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='exo',
            name='paid',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='paid'),
        ),
        migrations.AlterField(
            model_name='exo',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='exo',
            name='price_lab',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='exo',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='price'),
        ),
    ]
