# Generated by Django 4.2.1 on 2024-07-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0114_alter_exo_center_share_alter_exo_doctor_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exo',
            name='center_share',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='exo',
            name='doctor_share',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='exo',
            name='price_lab',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
    ]
