# Generated by Django 4.2.1 on 2024-07-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0116_alter_exo_center_share_alter_exo_doctor_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='proportion_center',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='proportion_doctor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
    ]
