# Generated by Django 4.2.1 on 2024-07-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0118_alter_doctors_proportion_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exo',
            name='price_lab',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='price'),
        ),
    ]
