# Generated by Django 4.2.1 on 2024-07-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0119_alter_exo_price_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exo',
            name='price_lab',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='price'),
        ),
    ]
