# Generated by Django 4.2.1 on 2024-07-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0129_prosthodontics_center_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exo',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='total_price'),
        ),
    ]
