# Generated by Django 4.2.1 on 2024-07-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0130_alter_exo_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xrays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('phone', models.CharField(max_length=120, verbose_name='Phone')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('date_of_birth', models.CharField(max_length=20, verbose_name='Gender')),
                ('ur', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ul', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lr', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ll', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='price')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='total_price')),
                ('type_xrays', models.CharField(max_length=20, null=True, verbose_name='Gender')),
                ('paid', models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='paid')),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Regdate')),
                ('exo_images', models.ImageField(blank=True, null=True, upload_to='')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.doctors')),
                ('educational', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.educational')),
                ('idReception', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception')),
                ('idReception1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception1')),
            ],
        ),
    ]
