# Generated by Django 4.2.1 on 2024-07-26 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0131_xrays'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='xrays_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.xrays'),
        ),
    ]
