# Generated by Django 4.2.1 on 2024-07-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0132_photo_xrays_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='xrays_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.xrays'),
        ),
    ]
