# Generated by Django 5.1.1 on 2024-09-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0137_endo_filling_type1_endo_filling_type2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
            ],
        ),
    ]
