# Generated by Django 5.1.1 on 2024-09-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0138_generatedbarcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endo',
            old_name='canal',
            new_name='canal_b',
        ),
        migrations.RenameField(
            model_name='endo',
            old_name='work_length',
            new_name='work_length_b',
        ),
        migrations.AddField(
            model_name='endo',
            name='canal_p',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='endo',
            name='work_length_p',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='work_length'),
        ),
    ]
