# Generated by Django 5.1.1 on 2024-09-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0139_rename_canal_endo_canal_b_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endo',
            old_name='canal_b',
            new_name='canal',
        ),
        migrations.RenameField(
            model_name='endo',
            old_name='work_length_b',
            new_name='work_length',
        ),
    ]
