# Generated by Django 5.1.1 on 2024-09-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0140_rename_canal_b_endo_canal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endo',
            old_name='canal',
            new_name='canal_b',
        ),
        migrations.RenameField(
            model_name='endo',
            old_name='work_length',
            new_name='work_length_b',
        ),
    ]
