# Generated by Django 5.1.1 on 2024-09-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0141_rename_canal_endo_canal_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endo',
            name='canal_acc',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='endo',
            name='canal_db',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='endo',
            name='canal_mb',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='endo',
            name='canal_p1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='endo',
            name='work_length_acc',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='work_length'),
        ),
        migrations.AddField(
            model_name='endo',
            name='work_length_db',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='work_length'),
        ),
        migrations.AddField(
            model_name='endo',
            name='work_length_mb',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='work_length'),
        ),
        migrations.AddField(
            model_name='endo',
            name='work_length_p1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='work_length'),
        ),
    ]
