# Generated by Django 5.1.1 on 2024-09-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0142_endo_canal_acc_endo_canal_db_endo_canal_mb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='invoice_num',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='fullname'),
        ),
    ]
