# Generated by Django 5.1.1 on 2024-09-27 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0143_alter_outcome_invoice_date_alter_outcome_invoice_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=120, null=True, verbose_name='Phone')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gender')),
                ('date_of_birth', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gender')),
                ('ur1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ul1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lr1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ll1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ur2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ul2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lr2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ll2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ur3', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ul3', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lr3', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ll3', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ur4', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ul4', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lr4', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ll4', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ur5', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ul5', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lr5', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ll5', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ur6', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ul6', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lr6', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ll6', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ur7', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ul7', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lr7', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ll7', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ur8', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ul8', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lr8', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ll8', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ur9', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ul9', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lr9', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ll9', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ur10', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ul10', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lr10', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ll10', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ur11', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ul11', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('lr11', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('ll11', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=0, max_digits=8, null=True, verbose_name='price')),
                ('regdate', models.DateTimeField(auto_now_add=True, verbose_name='Regdate')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.doctors')),
                ('educational', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.educational')),
                ('idReception', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception')),
                ('idReception1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception1')),
            ],
        ),
    ]
