# Generated by Django 5.1.1 on 2024-09-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0144_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='ll12',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='lr12',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='note',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='ul12',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='ur12',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
    ]
