# Generated by Django 5.1.1 on 2024-09-28 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0145_diagnosis_ll12_diagnosis_lr12_diagnosis_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='ll1',
            new_name='lle',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='lr1',
            new_name='lre',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='ul1',
            new_name='ule',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='ur1',
            new_name='ure',
        ),
    ]
