# Generated by Django 5.1.1 on 2024-09-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0146_rename_ll1_diagnosis_lle_rename_lr1_diagnosis_lre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='lle',
            new_name='ll',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='lre',
            new_name='lr',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='ule',
            new_name='ul',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='ure',
            new_name='ur',
        ),
    ]
