# Generated by Django 5.1.1 on 2024-09-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0147_rename_lle_diagnosis_ll_rename_lre_diagnosis_lr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='educational',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='idReception',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='idReception1',
        ),
    ]
