# Generated by Django 5.1.1 on 2024-09-28 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0148_remove_diagnosis_doctor_remove_diagnosis_educational_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='ll',
            new_name='ll1',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='lr',
            new_name='lr1',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='ul',
            new_name='ul1',
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='ur',
            new_name='ur1',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.doctors'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='educational',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.educational'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='idReception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='idReception1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.reception1'),
        ),
    ]
