# Generated by Django 5.1.1 on 2024-10-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0149_rename_ll_diagnosis_ll1_rename_lr_diagnosis_lr1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='ll4',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='lr4',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='ul4',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='ur4',
        ),
    ]
