# Generated by Django 5.1.1 on 2024-10-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0150_rename_ll4_diagnosis_type_remove_diagnosis_lr4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='note',
            new_name='note1',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='note10',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='note11',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='note12',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='note2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='note3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='note4',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='note5',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='note6',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='note7',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='note8',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='note9',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
    ]
