# Generated by Django 5.1.1 on 2024-10-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0151_rename_note_diagnosis_note1_diagnosis_note10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='note',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='reception1',
            name='note',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name'),
        ),
    ]
