# Generated by Django 5.1.1 on 2024-10-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0152_reception_note_reception1_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='endo',
            name='work_length_7',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='work_length'),
        ),
    ]
