# Generated by Django 4.2.1 on 2024-01-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
